# Generated by Django 4.1 on 2022-09-02 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facilitators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('skill', models.CharField(max_length=50)),
                ('stack', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1024)),
                ('email', models.EmailField(max_length=254)),
                ('organization', models.CharField(max_length=1024)),
                ('photo', models.ImageField(upload_to='./photos')),
            ],
        ),
    ]
